export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE'
export const UPDATE_TEAMS = 'UPDATE_TEAMS'
